[tasks.run]
command = "cargo"
args = [ "run" ]
env = { RUST_BACKTRACE = "full", INSTA_UPDATE = "always"}
watch=true
[tasks.test]
command = "cargo"
args = [ "test", "--", "--nocapture" ]
env = { RUST_BACKTRACE = "full", INSTA_UPDATE = "always"}
watch=true