import * as React from "react"
import { get } from "lodash"
import { FormStore } from "@xpfw/form"
import { MdExpandLess, MdExpandMore } from "react-icons/md"
import { observer } from "mobx-react"

const Credits: React.FunctionComponent<{
}> = (props) => {
  return (
    <div className="">
      <p>Dataset scraped from <a href="https://zenodo.org/record/3936556">a snapshot</a> of <a href="https://www.microsoft.com/en-us/research/project/microsoft-academic-graph/">Microsoft Academic Graph</a></p>
      <p>Scraping done via Rust and web interface built with JS.<br />External Library licenses for both are listed below.</p>
      <p>
        Rust:<br />
        Apache-2.0 (2): fasthash, fasthash-sys<br />
        Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT (1): wasi<br />
        Apache-2.0 OR BSL-1.0 (1): ryu<br />
        Apache-2.0 OR MIT (24): ahash, autocfg, cfg-if, chrono, gcc, hashbrown, itoa, libc, num-integer, num-traits, proc-macro2, quote, rand, rand_core, rand_core, serde, serde_derive, serde_json, syn, time, unicode-xid, winapi, winapi-i686-pc-windows-gnu, winapi-x86_64-pc-windows-gnu<br />
        ISC (1): rdrand<br />
        MIT (2): seahash, xoroshiro128<br />
        N/A (2): fuchsia-cprng, tlsurvey
      </p>
      <p>
        JS:<br />
        accepts licensed under MIT. Repository: jshttp/accepts<br />
        acorn licensed under MIT. Repository: https://github.com/acornjs/acorn.git<br />
        ajv licensed under MIT. Repository: https://github.com/ajv-validator/ajv.git<br />
        ajv-formats licensed under MIT. Repository: git+https://github.com/ajv-validator/ajv-formats.git<br />
        ansi-colors licensed under MIT. Repository: doowb/ansi-colors<br />
        ansi-html licensed under Apache-2.0. Repository: git://github.com/Tjatse/ansi-html.git<br />
        ansi-regex licensed under MIT. Repository: chalk/ansi-regex<br />
        ansi-styles licensed under MIT. Repository: chalk/ansi-styles<br />
        anymatch licensed under ISC. Repository: https://github.com/micromatch/anymatch<br />
        arr-diff licensed under MIT. Repository: jonschlinkert/arr-diff<br />
        arr-flatten licensed under MIT. Repository: jonschlinkert/arr-flatten<br />
        arr-union licensed under MIT. Repository: jonschlinkert/arr-union<br />
        array-flat-polyfill licensed under CC0-1.0. Repository: jonathantneal/array-flat-polyfill<br />
        array-flatten licensed under MIT. Repository: git://github.com/blakeembrey/array-flatten.git<br />
        array-union licensed under MIT. Repository: sindresorhus/array-union<br />
        array-uniq licensed under MIT. Repository: sindresorhus/array-uniq<br />
        array-unique licensed under MIT. Repository: jonschlinkert/array-unique<br />
        array.prototype.filter licensed under MIT. Repository: git+https://github.com/es-shims/Array.prototype.filter.git<br />
        assign-symbols licensed under MIT. Repository: jonschlinkert/assign-symbols<br />
        async-each licensed under MIT. Repository: git://github.com/paulmillr/async-each.git<br />
        async-limiter licensed under MIT. Repository: https://github.com/strml/async-limiter.git<br />
        atob licensed under (MIT OR Apache-2.0). Repository: git://git.coolaj86.com/coolaj86/atob.js.git<br />
        available-typed-arrays licensed under MIT. Repository: git+https://github.com/inspect-js/available-typed-arrays.git<br />
        awesome-typescript-loader licensed under MIT. Repository: https://github.com/s-panferov/awesome-typescript-loader.git<br />
        balanced-match licensed under MIT. Repository: git://github.com/juliangruber/balanced-match.git<br />
        base licensed under MIT. Repository: node-base/base<br />
        batch licensed under MIT. Repository: https://github.com/visionmedia/batch.git<br />
        big.js licensed under MIT. Repository: https://github.com/MikeMcl/big.js.git<br />
        binary-extensions licensed under MIT. Repository: sindresorhus/binary-extensions<br />
        body-parser licensed under MIT. Repository: expressjs/body-parser<br />
        bonjour licensed under MIT. Repository: https://github.com/watson/bonjour.git<br />
        brace-expansion licensed under MIT. Repository: git://github.com/juliangruber/brace-expansion.git<br />
        braces licensed under MIT. Repository: micromatch/braces<br />
        browserslist licensed under MIT. Repository: browserslist/browserslist<br />
        buffer-from licensed under MIT. Repository: LinusU/buffer-from<br />
        buffer-indexof licensed under MIT. Repository: git://github.com/soldair/node-buffer-indexof.git<br />
        bulma licensed under MIT. Repository: git+https://github.com/jgthms/bulma.git<br />
        bytes licensed under MIT. Repository: visionmedia/bytes.js<br />
        cache-base licensed under MIT. Repository: jonschlinkert/cache-base<br />
        call-bind licensed under MIT. Repository: git+https://github.com/ljharb/call-bind.git<br />
        camelcase licensed under MIT. Repository: sindresorhus/camelcase<br />
        caniuse-lite licensed under CC-BY-4.0. Repository: browserslist/caniuse-lite<br />
        chalk licensed under MIT. Repository: chalk/chalk<br />
        chokidar licensed under MIT. Repository: git+https://github.com/paulmillr/chokidar.git<br />
        chrome-trace-event licensed under MIT. Repository: github:samccone/chrome-trace-event<br />
        class-utils licensed under MIT. Repository: jonschlinkert/class-utils<br />
        cliui licensed under ISC. Repository: http://github.com/yargs/cliui.git<br />
        clone licensed under MIT. Repository: git://github.com/pvorb/node-clone.git<br />
        clone-deep licensed under MIT. Repository: jonschlinkert/clone-deep<br />
        collection-visit licensed under MIT. Repository: jonschlinkert/collection-visit<br />
        color-convert licensed under MIT. Repository: Qix-/color-convert<br />
        color-name licensed under MIT. Repository: git@github.com:dfcreative/color-name.git<br />
        colorette licensed under MIT. Repository: jorgebucaran/colorette<br />
        commander licensed under MIT. Repository: https://github.com/tj/commander.js.git<br />
        component-emitter licensed under MIT. Repository: https://github.com/component/emitter.git<br />
        compressible licensed under MIT. Repository: jshttp/compressible<br />
        compression licensed under MIT. Repository: expressjs/compression<br />
        concat-map licensed under MIT. Repository: git://github.com/substack/node-concat-map.git<br />
        connect-history-api-fallback licensed under MIT. Repository: http://github.com/bripkens/connect-history-api-fallback.git<br />
        content-disposition licensed under MIT. Repository: jshttp/content-disposition<br />
        content-type licensed under MIT. Repository: jshttp/content-type<br />
        cookie licensed under MIT. Repository: jshttp/cookie<br />
        cookie-signature licensed under MIT. Repository: https://github.com/visionmedia/node-cookie-signature.git<br />
        copy-descriptor licensed under MIT. Repository: jonschlinkert/copy-descriptor<br />
        core-util-is licensed under MIT. Repository: git://github.com/isaacs/core-util-is<br />
        cross-spawn licensed under MIT. Repository: git@github.com:moxystudio/node-cross-spawn.git<br />
        css-loader licensed under MIT. Repository: webpack-contrib/css-loader<br />
        cssesc licensed under MIT. Repository: https://github.com/mathiasbynens/cssesc.git<br />
        csstype licensed under MIT. Repository: https://github.com/frenic/csstype<br />
        d licensed under ISC. Repository: git://github.com/medikoo/d.git<br />
        d3-array licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-array.git<br />
        d3-color licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-color.git<br />
        d3-delaunay licensed under ISC. Repository: https://github.com/d3/d3-delaunay.git<br />
        d3-dispatch licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-dispatch.git<br />
        d3-dsv licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-dsv.git<br />
        d3-force licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-force.git<br />
        d3-format licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-format.git<br />
        d3-geo licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-geo.git<br />
        d3-geo-projection licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-geo-projection.git<br />
        d3-hierarchy licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-hierarchy.git<br />
        d3-interpolate licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-interpolate.git<br />
        d3-path licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-path.git<br />
        d3-quadtree licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-quadtree.git<br />
        d3-scale licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-scale.git<br />
        d3-shape licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-shape.git<br />
        d3-time licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-time.git<br />
        d3-time-format licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-time-format.git<br />
        d3-timer licensed under BSD-3-Clause. Repository: https://github.com/d3/d3-timer.git<br />
        debug licensed under MIT. Repository: git://github.com/visionmedia/debug.git<br />
        decamelize licensed under MIT. Repository: sindresorhus/decamelize<br />
        decode-uri-component licensed under MIT. Repository: SamVerschueren/decode-uri-component<br />
        deep-equal licensed under MIT. Repository: http://github.com/substack/node-deep-equal.git<br />
        default-gateway licensed under BSD-2-Clause. Repository: silverwind/default-gateway<br />
        define-properties licensed under MIT. Repository: git://github.com/ljharb/define-properties.git<br />
        define-property licensed under MIT. Repository: jonschlinkert/define-property<br />
        del licensed under MIT. Repository: sindresorhus/del<br />
        delaunator licensed under ISC. Repository: https://github.com/mapbox/delaunator.git<br />
        depd licensed under MIT. Repository: dougwilson/nodejs-depd<br />
        destroy licensed under MIT. Repository: stream-utils/destroy<br />
        detect-node licensed under MIT. Repository: https://github.com/iliakan/detect-node<br />
        dns-equal licensed under MIT. Repository: git+https://github.com/watson/dns-equal.git<br />
        dns-packet licensed under MIT. Repository: https://github.com/mafintosh/dns-packet<br />
        dns-txt licensed under MIT. Repository: https://github.com/watson/dns-txt.git<br />
        ee-first licensed under MIT. Repository: jonathanong/ee-first<br />
        electron-to-chromium licensed under ISC. Repository: https://github.com/kilian/electron-to-chromium/<br />
        emoji-regex licensed under MIT. Repository: https://github.com/mathiasbynens/emoji-regex.git<br />
        emojis-list licensed under MIT. Repository: git+https://github.com/kikobeats/emojis-list.git<br />
        encodeurl licensed under MIT. Repository: pillarjs/encodeurl<br />
        end-of-stream licensed under MIT. Repository: git://github.com/mafintosh/end-of-stream.git<br />
        envinfo licensed under MIT. Repository: https://github.com/tabrindle/envinfo<br />
        errno licensed under MIT. Repository: https://github.com/rvagg/node-errno.git<br />
        es-abstract licensed under MIT. Repository: git://github.com/ljharb/es-abstract.git<br />
        es-array-method-boxes-properly licensed under MIT. Repository: git+https://github.com/ljharb/es-array-method-boxes-properly.git<br />
        es-module-lexer licensed under MIT. Repository: git+https://github.com/guybedford/es-module-lexer.git<br />
        es-to-primitive licensed under MIT. Repository: git://github.com/ljharb/es-to-primitive.git<br />
        es5-ext licensed under ISC. Repository: medikoo/es5-ext<br />
        es6-iterator licensed under MIT. Repository: git://github.com/medikoo/es6-iterator.git<br />
        es6-symbol licensed under ISC. Repository: git://github.com/medikoo/es6-symbol.git<br />
        escalade licensed under MIT. Repository: lukeed/escalade<br />
        escape-html licensed under MIT. Repository: component/escape-html<br />
        escape-string-regexp licensed under MIT. Repository: sindresorhus/escape-string-regexp<br />
        eslint-scope licensed under BSD-2-Clause. Repository: eslint/eslint-scope<br />
        esrecurse licensed under BSD-2-Clause. Repository: https://github.com/estools/esrecurse.git<br />
        estraverse licensed under BSD-2-Clause. Repository: http://github.com/estools/estraverse.git<br />
        etag licensed under MIT. Repository: jshttp/etag<br />
        eventemitter3 licensed under MIT. Repository: git://github.com/primus/eventemitter3.git<br />
        events licensed under MIT. Repository: git://github.com/Gozala/events.git<br />
        eventsource licensed under MIT. Repository: git://github.com/EventSource/eventsource.git<br />
        execa licensed under MIT. Repository: sindresorhus/execa<br />
        expand-brackets licensed under MIT. Repository: jonschlinkert/expand-brackets<br />
        express licensed under MIT. Repository: expressjs/express<br />
        ext licensed under ISC. Repository: https://github.com/medikoo/es5-ext/tree/ext<br />
        extend-shallow licensed under MIT. Repository: jonschlinkert/extend-shallow<br />
        extglob licensed under MIT. Repository: micromatch/extglob<br />
        fast-deep-equal licensed under MIT. Repository: git+https://github.com/epoberezkin/fast-deep-equal.git<br />
        fast-json-patch licensed under MIT. Repository: git://github.com/Starcounter-Jack/JSON-Patch.git<br />
        fast-json-stable-stringify licensed under MIT. Repository: git://github.com/epoberezkin/fast-json-stable-stringify.git<br />
        fastest-levenshtein licensed under MIT. Repository: git+https://github.com/ka-weihe/fastest-levenshtein.git<br />
        faye-websocket licensed under Apache-2.0. Repository: git://github.com/faye/faye-websocket-node.git<br />
        file-loader licensed under MIT. Repository: webpack-contrib/file-loader<br />
        fill-range licensed under MIT. Repository: jonschlinkert/fill-range<br />
        finalhandler licensed under MIT. Repository: pillarjs/finalhandler<br />
        find-up licensed under MIT. Repository: sindresorhus/find-up<br />
        follow-redirects licensed under MIT. Repository: git@github.com:follow-redirects/follow-redirects.git<br />
        for-in licensed under MIT. Repository: jonschlinkert/for-in<br />
        foreach licensed under MIT. Repository: git://github.com/manuelstofer/foreach<br />
        forwarded licensed under MIT. Repository: jshttp/forwarded<br />
        fragment-cache licensed under MIT. Repository: jonschlinkert/fragment-cache<br />
        fresh licensed under MIT. Repository: jshttp/fresh<br />
        fs.realpath licensed under ISC. Repository: git+https://github.com/isaacs/fs.realpath.git<br />
        function-bind licensed under MIT. Repository: git://github.com/Raynos/function-bind.git<br />
        get-caller-file licensed under ISC. Repository: git+https://github.com/stefanpenner/get-caller-file.git<br />
        get-intrinsic licensed under MIT. Repository: git+https://github.com/ljharb/get-intrinsic.git<br />
        get-stream licensed under MIT. Repository: sindresorhus/get-stream<br />
        get-value licensed under MIT. Repository: jonschlinkert/get-value<br />
        glob licensed under ISC. Repository: git://github.com/isaacs/node-glob.git<br />
        glob-parent licensed under ISC. Repository: https://github.com/es128/glob-parent<br />
        glob-to-regexp licensed under BSD-2-Clause. Repository: https://github.com/fitzgen/glob-to-regexp.git<br />
        globby licensed under MIT. Repository: sindresorhus/globby<br />
        graceful-fs licensed under ISC. Repository: https://github.com/isaacs/node-graceful-fs<br />
        handle-thing licensed under MIT. Repository: git+ssh://git@github.com/indutny/handle-thing.git<br />
        has licensed under MIT. Repository: git://github.com/tarruda/has.git<br />
        has-bigints licensed under MIT. Repository: git+https://github.com/ljharb/has-bigints.git<br />
        has-flag licensed under MIT. Repository: sindresorhus/has-flag<br />
        has-symbols licensed under MIT. Repository: git://github.com/inspect-js/has-symbols.git<br />
        has-value licensed under MIT. Repository: jonschlinkert/has-value<br />
        has-values licensed under MIT. Repository: jonschlinkert/has-values<br />
        hpack.js licensed under MIT. Repository: git+ssh://git@github.com/indutny/hpack.js.git<br />
        html-entities licensed under MIT. Repository: https://github.com/mdevils/node-html-entities.git<br />
        http-deceiver licensed under MIT. Repository: git+ssh://git@github.com/indutny/http-deceiver.git<br />
        http-errors licensed under MIT. Repository: jshttp/http-errors<br />
        http-parser-js licensed under MIT. Repository: git://github.com/creationix/http-parser-js.git<br />
        http-proxy licensed under MIT. Repository: https://github.com/http-party/node-http-proxy.git<br />
        http-proxy-middleware licensed under MIT. Repository: https://github.com/chimurai/http-proxy-middleware.git<br />
        human-signals licensed under Apache-2.0. Repository: ehmicky/human-signals<br />
        iconv-lite licensed under MIT. Repository: git://github.com/ashtuchkin/iconv-lite.git<br />
        icss-utils licensed under ISC. Repository: git+https://github.com/css-modules/icss-utils.git<br />
        immediate licensed under MIT. Repository: git://github.com/calvinmetcalf/immediate.git<br />
        import-local licensed under MIT. Repository: sindresorhus/import-local<br />
        inflight licensed under ISC. Repository: https://github.com/npm/inflight.git<br />
        inherits licensed under ISC. Repository: git://github.com/isaacs/inherits<br />
        internal-ip licensed under MIT. Repository: sindresorhus/internal-ip<br />
        internmap licensed under ISC. Repository: https://github.com/mbostock/internmap.git<br />
        interpret licensed under MIT. Repository: gulpjs/interpret<br />
        ip licensed under MIT. Repository: http://github.com/indutny/node-ip.git<br />
        ip-regex licensed under MIT. Repository: sindresorhus/ip-regex<br />
        ipaddr.js licensed under MIT. Repository: git://github.com/whitequark/ipaddr.js<br />
        is-absolute-url licensed under MIT. Repository: sindresorhus/is-absolute-url<br />
        is-accessor-descriptor licensed under MIT. Repository: jonschlinkert/is-accessor-descriptor<br />
        is-arguments licensed under MIT. Repository: git://github.com/inspect-js/is-arguments.git<br />
        is-bigint licensed under MIT. Repository: git+https://github.com/inspect-js/is-bigint.git<br />
        is-binary-path licensed under MIT. Repository: sindresorhus/is-binary-path<br />
        is-boolean-object licensed under MIT. Repository: git://github.com/inspect-js/is-boolean-object.git<br />
        is-buffer licensed under MIT. Repository: git://github.com/feross/is-buffer.git<br />
        is-callable licensed under MIT. Repository: git://github.com/ljharb/is-callable.git<br />
        is-core-module licensed under MIT. Repository: git+https://github.com/inspect-js/is-core-module.git<br />
        is-data-descriptor licensed under MIT. Repository: jonschlinkert/is-data-descriptor<br />
        is-date-object licensed under MIT. Repository: git://github.com/inspect-js/is-date-object.git<br />
        is-descriptor licensed under MIT. Repository: jonschlinkert/is-descriptor<br />
        is-extendable licensed under MIT. Repository: jonschlinkert/is-extendable<br />
        is-extglob licensed under MIT. Repository: jonschlinkert/is-extglob<br />
        is-fullwidth-code-point licensed under MIT. Repository: sindresorhus/is-fullwidth-code-point<br />
        is-generator-function licensed under MIT. Repository: git://github.com/inspect-js/is-generator-function.git<br />
        is-glob licensed under MIT. Repository: micromatch/is-glob<br />
        is-negative-zero licensed under MIT. Repository: git://github.com/inspect-js/is-negative-zero.git<br />
        is-number licensed under MIT. Repository: jonschlinkert/is-number<br />
        is-number-object licensed under MIT. Repository: git://github.com/inspect-js/is-number-object.git<br />
        is-path-cwd licensed under MIT. Repository: sindresorhus/is-path-cwd<br />
        is-path-in-cwd licensed under MIT. Repository: sindresorhus/is-path-in-cwd<br />
        is-path-inside licensed under MIT. Repository: sindresorhus/is-path-inside<br />
        is-plain-object licensed under MIT. Repository: jonschlinkert/is-plain-object<br />
        is-regex licensed under MIT. Repository: git://github.com/inspect-js/is-regex.git<br />
        is-stream licensed under MIT. Repository: sindresorhus/is-stream<br />
        is-string licensed under MIT. Repository: git://github.com/ljharb/is-string.git<br />
        is-symbol licensed under MIT. Repository: git://github.com/inspect-js/is-symbol.git<br />
        is-typed-array licensed under MIT. Repository: git://github.com/inspect-js/is-typed-array.git<br />
        is-windows licensed under MIT. Repository: jonschlinkert/is-windows<br />
        is-wsl licensed under MIT. Repository: sindresorhus/is-wsl<br />
        isarray licensed under MIT. Repository: git://github.com/juliangruber/isarray.git<br />
        isexe licensed under ISC. Repository: git+https://github.com/isaacs/isexe.git<br />
        isobject licensed under MIT. Repository: jonschlinkert/isobject<br />
        jest-worker licensed under MIT. Repository: https://github.com/facebook/jest.git<br />
        js-tokens licensed under MIT. Repository: lydell/js-tokens<br />
        json-parse-better-errors licensed under MIT. Repository: https://github.com/zkat/json-parse-better-errors<br />
        json-schema-traverse licensed under MIT. Repository: git+https://github.com/epoberezkin/json-schema-traverse.git<br />
        json-stringify-pretty-compact licensed under MIT. Repository: lydell/json-stringify-pretty-compact<br />
        json3 licensed under MIT. Repository: git://github.com/bestiejs/json3.git<br />
        json5 licensed under MIT. Repository: git+https://github.com/json5/json5.git<br />
        killable licensed under ISC. Repository: https://github.com/marten-de-vries/killable.git<br />
        kind-of licensed under MIT. Repository: jonschlinkert/kind-of<br />
        klona licensed under MIT. Repository: lukeed/klona<br />
        lie licensed under MIT. Repository: https://github.com/calvinmetcalf/lie.git<br />
        loader-runner licensed under MIT. Repository: git+https://github.com/webpack/loader-runner.git<br />
        loader-utils licensed under MIT. Repository: https://github.com/webpack/loader-utils.git<br />
        localforage licensed under Apache-2.0. Repository: git://github.com/localForage/localForage.git<br />
        locate-path licensed under MIT. Repository: sindresorhus/locate-path<br />
        lodash licensed under MIT. Repository: lodash/lodash<br />
        log-symbols licensed under MIT. Repository: sindresorhus/log-symbols<br />
        loglevel licensed under MIT. Repository: git://github.com/pimterry/loglevel.git<br />
        loglevelnext licensed under MIT. Repository: shellscape/loglevelnext<br />
        loose-envify licensed under MIT. Repository: git://github.com/zertosh/loose-envify.git<br />
        lru-cache licensed under ISC. Repository: git://github.com/isaacs/node-lru-cache.git<br />
        map-cache licensed under MIT. Repository: jonschlinkert/map-cache<br />
        map-visit licensed under MIT. Repository: jonschlinkert/map-visit<br />
        media-typer licensed under MIT. Repository: jshttp/media-typer<br />
        memory-fs licensed under MIT. Repository: https://github.com/webpack/memory-fs.git<br />
        merge-descriptors licensed under MIT. Repository: component/merge-descriptors<br />
        merge-stream licensed under MIT. Repository: grncdr/merge-stream<br />
        methods licensed under MIT. Repository: jshttp/methods<br />
        micromatch licensed under MIT. Repository: micromatch/micromatch<br />
        mime licensed under MIT. Repository: https://github.com/broofa/mime<br />
        mime-db licensed under MIT. Repository: jshttp/mime-db<br />
        mime-types licensed under MIT. Repository: jshttp/mime-types<br />
        mimic-fn licensed under MIT. Repository: sindresorhus/mimic-fn<br />
        minimalistic-assert licensed under ISC. Repository: https://github.com/calvinmetcalf/minimalistic-assert.git<br />
        minimatch licensed under ISC. Repository: git://github.com/isaacs/minimatch.git<br />
        minimist licensed under MIT. Repository: git://github.com/substack/minimist.git<br />
        mixin-deep licensed under MIT. Repository: jonschlinkert/mixin-deep<br />
        mkdirp licensed under MIT. Repository: https://github.com/substack/node-mkdirp.git<br />
        mobx licensed under MIT. Repository: https://github.com/mobxjs/mobx.git<br />
        mobx-react licensed under MIT. Repository: https://github.com/mobxjs/mobx.git<br />
        moment licensed under MIT. Repository: https://github.com/moment/moment.git<br />
        ms licensed under MIT. Repository: zeit/ms<br />
        multicast-dns licensed under MIT. Repository: https://github.com/mafintosh/multicast-dns.git<br />
        multicast-dns-service-types licensed under MIT. Repository: https://github.com/mafintosh/multicast-dns-service-types.git<br />
        nanoid licensed under MIT. Repository: ai/nanoid<br />
        nanomatch licensed under MIT. Repository: micromatch/nanomatch<br />
        nedb licensed under SEE LICENSE IN LICENSE. Repository: git@github.com:louischatriot/nedb.git<br />
        negotiator licensed under MIT. Repository: jshttp/negotiator<br />
        neo-async licensed under MIT. Repository: git@github.com:suguru03/neo-async.git<br />
        next-tick licensed under MIT. Repository: git://github.com/medikoo/next-tick.git<br />
        nice-try licensed under MIT. Repository: https://github.com/electerious/nice-try.git<br />
        node-fetch licensed under MIT. Repository: https://github.com/bitinn/node-fetch.git<br />
        node-forge licensed under (BSD-3-Clause OR GPL-2.0). Repository: https://github.com/digitalbazaar/forge<br />
        node-releases licensed under MIT. Repository: git+https://github.com/chicoxyzzy/node-releases.git<br />
        normalize-path licensed under MIT. Repository: jonschlinkert/normalize-path<br />
        npm-run-path licensed under MIT. Repository: sindresorhus/npm-run-path<br />
        object-assign licensed under MIT. Repository: sindresorhus/object-assign<br />
        object-copy licensed under MIT. Repository: jonschlinkert/object-copy<br />
        object-inspect licensed under MIT. Repository: git://github.com/inspect-js/object-inspect.git<br />
        object-is licensed under MIT. Repository: git://github.com/es-shims/object-is.git<br />
        object-keys licensed under MIT. Repository: git://github.com/ljharb/object-keys.git<br />
        object-visit licensed under MIT. Repository: jonschlinkert/object-visit<br />
        object.assign licensed under MIT. Repository: git://github.com/ljharb/object.assign.git<br />
        object.pick licensed under MIT. Repository: jonschlinkert/object.pick<br />
        obuf licensed under MIT. Repository: git@github.com:indutny/offset-buffer<br />
        on-finished licensed under MIT. Repository: jshttp/on-finished<br />
        on-headers licensed under MIT. Repository: jshttp/on-headers<br />
        once licensed under ISC. Repository: git://github.com/isaacs/once<br />
        onetime licensed under MIT. Repository: sindresorhus/onetime<br />
        opn licensed under MIT. Repository: sindresorhus/opn<br />
        original licensed under MIT. Repository: https://github.com/unshiftio/original<br />
        p-finally licensed under MIT. Repository: sindresorhus/p-finally<br />
        p-limit licensed under MIT. Repository: sindresorhus/p-limit<br />
        p-locate licensed under MIT. Repository: sindresorhus/p-locate<br />
        p-map licensed under MIT. Repository: sindresorhus/p-map<br />
        p-retry licensed under MIT. Repository: sindresorhus/p-retry<br />
        p-try licensed under MIT. Repository: sindresorhus/p-try<br />
        parseurl licensed under MIT. Repository: pillarjs/parseurl<br />
        pascalcase licensed under MIT. Repository: jonschlinkert/pascalcase<br />
        path-browserify licensed under MIT. Repository: git://github.com/browserify/path-browserify.git<br />
        path-dirname licensed under MIT. Repository: es128/path-dirname<br />
        path-exists licensed under MIT. Repository: sindresorhus/path-exists<br />
        path-is-absolute licensed under MIT. Repository: sindresorhus/path-is-absolute<br />
        path-is-inside licensed under (WTFPL OR MIT). Repository: domenic/path-is-inside<br />
        path-key licensed under MIT. Repository: sindresorhus/path-key<br />
        path-parse licensed under MIT. Repository: https://github.com/jbgutierrez/path-parse.git<br />
        path-to-regexp licensed under MIT. Repository: https://github.com/component/path-to-regexp.git<br />
        picomatch licensed under MIT. Repository: micromatch/picomatch<br />
        pify licensed under MIT. Repository: sindresorhus/pify<br />
        pinkie licensed under MIT. Repository: floatdrop/pinkie<br />
        pinkie-promise licensed under MIT. Repository: floatdrop/pinkie-promise<br />
        pkg-dir licensed under MIT. Repository: sindresorhus/pkg-dir<br />
        portfinder licensed under MIT. Repository: git@github.com:http-party/node-portfinder.git<br />
        posix-character-classes licensed under MIT. Repository: jonschlinkert/posix-character-classes<br />
        postcss licensed under MIT. Repository: postcss/postcss<br />
        postcss-modules-extract-imports licensed under ISC. Repository: https://github.com/css-modules/postcss-modules-extract-imports.git<br />
        postcss-modules-local-by-default licensed under MIT. Repository: https://github.com/css-modules/postcss-modules-local-by-default.git<br />
        postcss-modules-scope licensed under ISC. Repository: https://github.com/css-modules/postcss-modules-scope.git<br />
        postcss-modules-values licensed under ISC. Repository: git+https://github.com/css-modules/postcss-modules-values.git<br />
        postcss-selector-parser licensed under MIT. Repository: postcss/postcss-selector-parser<br />
        postcss-value-parser licensed under MIT. Repository: https://github.com/TrySound/postcss-value-parser.git<br />
        process licensed under MIT. Repository: git://github.com/shtylman/node-process.git<br />
        process-nextick-args licensed under MIT. Repository: https://github.com/calvinmetcalf/process-nextick-args.git<br />
        prop-types licensed under MIT. Repository: facebook/prop-types<br />
        proxy-addr licensed under MIT. Repository: jshttp/proxy-addr<br />
        prr licensed under MIT. Repository: https://github.com/rvagg/prr.git<br />
        pump licensed under MIT. Repository: git://github.com/mafintosh/pump.git<br />
        punycode licensed under MIT. Repository: https://github.com/bestiejs/punycode.js.git<br />
        qs licensed under BSD-3-Clause. Repository: https://github.com/ljharb/qs.git<br />
        querystringify licensed under MIT. Repository: https://github.com/unshiftio/querystringify<br />
        randombytes licensed under MIT. Repository: git@github.com:crypto-browserify/randombytes.git<br />
        range-parser licensed under MIT. Repository: jshttp/range-parser<br />
        raw-body licensed under MIT. Repository: stream-utils/raw-body<br />
        react licensed under MIT. Repository: https://github.com/facebook/react.git<br />
        react-dom licensed under MIT. Repository: https://github.com/facebook/react.git<br />
        react-icons licensed under MIT. Repository: git+ssh://git@github.com:react-icons/react-icons.git<br />
        react-is licensed under MIT. Repository: https://github.com/facebook/react.git<br />
        react-vega licensed under Apache-2.0. Repository: git@github.com:vega/react-vega.git<br />
        readable-stream licensed under MIT. Repository: git://github.com/nodejs/readable-stream<br />
        readdirp licensed under MIT. Repository: git://github.com/paulmillr/readdirp.git<br />
        rechoir licensed under MIT. Repository: gulpjs/rechoir<br />
        regex-not licensed under MIT. Repository: jonschlinkert/regex-not<br />
        regexp.prototype.flags licensed under MIT. Repository: git://github.com/es-shims/RegExp.prototype.flags.git<br />
        remove-trailing-separator licensed under ISC. Repository: git+https://github.com/darsain/remove-trailing-separator.git<br />
        repeat-element licensed under MIT. Repository: jonschlinkert/repeat-element<br />
        repeat-string licensed under MIT. Repository: jonschlinkert/repeat-string<br />
        require-directory licensed under MIT. Repository: git://github.com/troygoode/node-require-directory.git<br />
        require-from-string licensed under MIT. Repository: floatdrop/require-from-string<br />
        require-main-filename licensed under ISC. Repository: git+ssh://git@github.com/yargs/require-main-filename.git<br />
        requires-port licensed under MIT. Repository: https://github.com/unshiftio/requires-port<br />
        resolve licensed under MIT. Repository: git://github.com/browserify/resolve.git<br />
        resolve-cwd licensed under MIT. Repository: sindresorhus/resolve-cwd<br />
        resolve-from licensed under MIT. Repository: sindresorhus/resolve-from<br />
        resolve-url licensed under MIT. Repository: lydell/resolve-url<br />
        ret licensed under MIT. Repository: git://github.com/fent/ret.js.git<br />
        retry licensed under MIT. Repository: git://github.com/tim-kos/node-retry.git<br />
        rimraf licensed under ISC. Repository: git://github.com/isaacs/rimraf.git<br />
        rw licensed under BSD-3-Clause. Repository: http://github.com/mbostock/rw.git<br />
        safe-buffer licensed under MIT. Repository: git://github.com/feross/safe-buffer.git<br />
        safe-regex licensed under MIT. Repository: git://github.com/substack/safe-regex.git<br />
        safer-buffer licensed under MIT. Repository: git+https://github.com/ChALkeR/safer-buffer.git<br />
        sass licensed under MIT. Repository: https://github.com/sass/dart-sass<br />
        sass-loader licensed under MIT. Repository: webpack-contrib/sass-loader<br />
        scheduler licensed under MIT. Repository: https://github.com/facebook/react.git<br />
        schema-utils licensed under MIT. Repository: webpack/schema-utils<br />
        select-hose licensed under MIT. Repository: git+ssh://git@github.com/indutny/select-hose.git<br />
        selfsigned licensed under MIT. Repository: git://github.com/jfromaniello/selfsigned.git<br />
        semver licensed under ISC. Repository: https://github.com/npm/node-semver<br />
        send licensed under MIT. Repository: pillarjs/send<br />
        serialize-javascript licensed under BSD-3-Clause. Repository: git+https://github.com/yahoo/serialize-javascript.git<br />
        serve-index licensed under MIT. Repository: expressjs/serve-index<br />
        serve-static licensed under MIT. Repository: expressjs/serve-static<br />
        set-blocking licensed under ISC. Repository: git+https://github.com/yargs/set-blocking.git<br />
        set-value licensed under MIT. Repository: jonschlinkert/set-value<br />
        setprototypeof licensed under ISC. Repository: https://github.com/wesleytodd/setprototypeof.git<br />
        shallow-clone licensed under MIT. Repository: jonschlinkert/shallow-clone<br />
        shebang-command licensed under MIT. Repository: kevva/shebang-command<br />
        shebang-regex licensed under MIT. Repository: sindresorhus/shebang-regex<br />
        signal-exit licensed under ISC. Repository: https://github.com/tapjs/signal-exit.git<br />
        snapdragon licensed under MIT. Repository: jonschlinkert/snapdragon<br />
        snapdragon-node licensed under MIT. Repository: jonschlinkert/snapdragon-node<br />
        snapdragon-util licensed under MIT. Repository: jonschlinkert/snapdragon-util<br />
        sockjs licensed under MIT. Repository: https://github.com/sockjs/sockjs-node.git<br />
        sockjs-client licensed under MIT. Repository: https://github.com/sockjs/sockjs-client.git<br />
        source-list-map licensed under MIT. Repository: https://github.com/webpack/source-list-map.git<br />
        source-map licensed under BSD-3-Clause. Repository: http://github.com/mozilla/source-map.git<br />
        source-map-js licensed under BSD-3-Clause. Repository: http://github.com/7rulnik/source-map.git<br />
        source-map-resolve licensed under MIT. Repository: lydell/source-map-resolve<br />
        source-map-support licensed under MIT. Repository: https://github.com/evanw/node-source-map-support<br />
        source-map-url licensed under MIT. Repository: lydell/source-map-url<br />
        spdy licensed under MIT. Repository: git://github.com/indutny/node-spdy.git<br />
        spdy-transport licensed under MIT. Repository: git://github.com/spdy-http2/spdy-transport.git<br />
        split-string licensed under MIT. Repository: jonschlinkert/split-string<br />
        static-extend licensed under MIT. Repository: jonschlinkert/static-extend<br />
        statuses licensed under MIT. Repository: jshttp/statuses<br />
        string-width licensed under MIT. Repository: sindresorhus/string-width<br />
        string.prototype.trimend licensed under MIT. Repository: git://github.com/es-shims/String.prototype.trimEnd.git<br />
        string.prototype.trimstart licensed under MIT. Repository: git://github.com/es-shims/String.prototype.trimStart.git<br />
        string_decoder licensed under MIT. Repository: git://github.com/nodejs/string_decoder.git<br />
        strip-ansi licensed under MIT. Repository: chalk/strip-ansi<br />
        strip-eof licensed under MIT. Repository: sindresorhus/strip-eof<br />
        strip-final-newline licensed under MIT. Repository: sindresorhus/strip-final-newline<br />
        style-loader licensed under MIT. Repository: webpack-contrib/style-loader<br />
        supports-color licensed under MIT. Repository: chalk/supports-color<br />
        tapable licensed under MIT. Repository: http://github.com/webpack/tapable.git<br />
        terser licensed under BSD-2-Clause. Repository: https://github.com/terser/terser<br />
        terser-webpack-plugin licensed under MIT. Repository: webpack-contrib/terser-webpack-plugin<br />
        thunky licensed under MIT. Repository: git://github.com/mafintosh/thunky.git<br />
        to-object-path licensed under MIT. Repository: jonschlinkert/to-object-path<br />
        to-regex licensed under MIT. Repository: jonschlinkert/to-regex<br />
        to-regex-range licensed under MIT. Repository: micromatch/to-regex-range<br />
        toidentifier licensed under MIT. Repository: component/toidentifier<br />
        topojson-client licensed under ISC. Repository: https://github.com/topojson/topojson-client.git<br />
        tslib licensed under 0BSD. Repository: https://github.com/Microsoft/tslib.git<br />
        type licensed under ISC. Repository: medikoo/type<br />
        type-is licensed under MIT. Repository: jshttp/type-is<br />
        typescript licensed under Apache-2.0. Repository: https://github.com/Microsoft/TypeScript.git<br />
        unbox-primitive licensed under MIT. Repository: git+https://github.com/ljharb/unbox-primitive.git<br />
        union-value licensed under MIT. Repository: jonschlinkert/union-value<br />
        unpipe licensed under MIT. Repository: stream-utils/unpipe<br />
        unset-value licensed under MIT. Repository: jonschlinkert/unset-value<br />
        upath licensed under MIT. Repository: git://github.com/anodynos/upath<br />
        uri-js licensed under BSD-2-Clause. Repository: http://github.com/garycourt/uri-js<br />
        urix licensed under MIT. Repository: lydell/urix<br />
        url licensed under MIT. Repository: https://github.com/defunctzombie/node-url.git<br />
        url-parse licensed under MIT. Repository: https://github.com/unshiftio/url-parse.git<br />
        use licensed under MIT. Repository: jonschlinkert/use<br />
        util licensed under MIT. Repository: git://github.com/browserify/node-util<br />
        util-deprecate licensed under MIT. Repository: git://github.com/TooTallNate/util-deprecate.git<br />
        utils-merge licensed under MIT. Repository: git://github.com/jaredhanson/utils-merge.git<br />
        uuid licensed under MIT. Repository: https://github.com/uuidjs/uuid.git<br />
        v8-compile-cache licensed under MIT. Repository: https://github.com/zertosh/v8-compile-cache.git<br />
        vary licensed under MIT. Repository: jshttp/vary<br />
        vega licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-canvas licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-crossfilter licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-dataflow licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-embed licensed under BSD-3-Clause. Repository: http://github.com/vega/vega-embed.git<br />
        vega-encode licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-event-selector licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-expression licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-force licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-format licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-functions licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-geo licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-hierarchy licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-label licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-lite licensed under BSD-3-Clause. Repository: https://github.com/vega/vega-lite.git<br />
        vega-loader licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-parser licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-projection licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-regression licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-runtime licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-scale licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-scenegraph licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-schema-url-parser licensed under BSD-3-Clause. Repository: git@github.com:vega/schema.git<br />
        vega-selections licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-statistics licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-themes licensed under BSD-3-Clause. Repository: https://github.com/vega/vega-themes.git<br />
        vega-time licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-tooltip licensed under BSD-3-Clause. Repository: https://github.com/vega/vega-tooltip.git<br />
        vega-transforms licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-typings licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-util licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-view licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-view-transforms licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-voronoi licensed under BSD-3-Clause. Repository: vega/vega<br />
        vega-wordcloud licensed under BSD-3-Clause. Repository: vega/vega<br />
        watchpack licensed under MIT. Repository: https://github.com/webpack/watchpack.git<br />
        wbuf licensed under MIT. Repository: git@github.com:indutny/wbuf<br />
        webpack licensed under MIT. Repository: https://github.com/webpack/webpack.git<br />
        webpack-cli licensed under MIT. Repository: https://github.com/webpack/webpack-cli.git<br />
        webpack-dev-middleware licensed under MIT. Repository: webpack/webpack-dev-middleware<br />
        webpack-dev-server licensed under MIT. Repository: https://github.com/webpack/webpack-dev-server.git<br />
        webpack-log licensed under MIT. Repository: https://github.com/webpack-contrib/webpack-log.git<br />
        webpack-merge licensed under MIT. Repository: https://github.com/survivejs/webpack-merge.git<br />
        webpack-sources licensed under MIT. Repository: git+https://github.com/webpack/webpack-sources.git<br />
        websocket-driver licensed under Apache-2.0. Repository: git://github.com/faye/websocket-driver-node.git<br />
        websocket-extensions licensed under Apache-2.0. Repository: git://github.com/faye/websocket-extensions-node.git<br />
        which licensed under ISC. Repository: git://github.com/isaacs/node-which.git<br />
        which-boxed-primitive licensed under MIT. Repository: git+https://github.com/inspect-js/which-boxed-primitive.git<br />
        which-module licensed under ISC. Repository: git+https://github.com/nexdrew/which-module.git<br />
        which-typed-array licensed under MIT. Repository: git://github.com/inspect-js/which-typed-array.git<br />
        wildcard licensed under MIT. Repository: git://github.com/DamonOehlman/wildcard.git<br />
        wrap-ansi licensed under MIT. Repository: chalk/wrap-ansi<br />
        wrappy licensed under ISC. Repository: https://github.com/npm/wrappy<br />
        ws licensed under MIT. Repository: websockets/ws<br />
        y18n licensed under ISC. Repository: git@github.com:yargs/y18n.git<br />
        yallist licensed under ISC. Repository: git+https://github.com/isaacs/yallist.git<br />
        yargs licensed under MIT. Repository: https://github.com/yargs/yargs.git<br />
        yargs-parser licensed under ISC. Repository: git@github.com:yargs/yargs-parser.git<br />
        yocto-queue licensed under MIT. Repository: sindresorhus/yocto-queue<br />

      </p>
    </div>
  )
}

export default Credits
